server.port: 8083
server.contextPath: /BookApi

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.17:3306/hmis_db_4?useSSL=false
    username: root
    password: hm!s@dm!n
  secondDatasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.11:3306/hmis_db_4?useSSL=false
    username: root
    password: Hmis@Dmin 
    
    